spring:
  data:
    mongodb:
      uri: mongodb+srv://vignesh:b3vdocq9lHFxIQtb@ruchinique-development.q8r8j83.mongodb.net/ruchinique?retryWrites=true&w=majority&readPreference=secondaryPreferred&maxStalenessSeconds=120

